#!/bin/sh

BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT='#FFFFFF'
TEXT='#FFFFFF'
WRONG='#000000'
VERIFYING='#000000'

i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$TEXT          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 5                     \
--clock                      \
--indicator                  \
--time-str="%H:%M:%S"        \
--radius 200 \
--ring-width 8 \
--time-size=70 \
--date-size=20 \
--date-pos="x+w/2:y+85+h/2" \
-F \
--date-str="%A, %Y-%m-%d"             


# --image=/home/hchothani/wallpaper/Polygonal.jpg
# --raw=2560x1440:rgb
