#!/bin/sh

xrandr | grep -v eDP-1 | grep -q "DP-1 connected"
ST=$?

if [ $ST -eq 0 ]; then
    xrandr --output eDP-1 --mode 1920x1200 --output DP-1 --auto --primary --left-of eDP-1
else
  xrandr | grep -q "HDMI-1 connected"
  ST=$?
  if [ $ST -eq 0 ]; then
      xrandr --output eDP-1 --mode 1920x1200 --output HDMI-1 --auto --primary --left-of eDP-1
  else
      xrandr --output eDP-1 --mode 1920x1200 --primary
  fi
fi

# Send first 4 workspaces to primary output
i3-msg '[workspace="^(1|2|3|4|5|6|7|8|9|10)"] exec send_to_primary;'

#xrandr | grep -q HDMI1 && xrandr --output eDP1 --mode 1920x1200 --output HDMI-1 --auto --primary --left-of eDP1
