#!/bin/bash

if [[ $(xrandr -q | grep 'DisplayPort-2 connected') ]]; then
	xrandr --output eDP-1 --mode 2560x1600 --rotate normal --output DisplayPort-2 --primary --mode 2560x1440 --rotate normal --left-of eDP-1
else
	xrandr --output eDP-1 --primary --mode 2560x1600

	for i in {1..10}; do

		i3-msg workspace $i output eDP-1  
#  		i3-msg workspace $i && i3-msgmove workspace to output eDP-1
	done


fi

feh --bg-scale ~/pictures/wallpaper/cranewater.jpg


# i3-msg move workspace to output 'eDP-1' 
