#! /bin/bash

output='/home/hchothani/pictures/screenshots/%T-%d-%m-%Y-screenshot.png'

case "$1" in 
  "select") scrot "$output" --select || exit;;
  "window") scrot "$output" --focused --border || exit;;
  *) scrot "$output" || exit;;
esac

# notify-send "Screenshot Taken."
